use std::{
    ffi::OsString,
    fmt::{
        Display,
        Formatter,
        Result as FmtResult,
    },
    num::ParseIntError,
};
// For doc comment reference
#[allow(unused_imports)]
use std::num::NonZeroUsize;

use crate::consts::*;

/// All errors generated by this program are variants of this [Error] type.  See the [Error] type's variants for more
/// details.
#[derive(Debug, PartialEq)]
pub enum Error {
    /// Returned when a provided argument is not convertible to `UTF-8` (required in order to be a [String] in Rust).
    /// The argument is provided as this variant's payload to facilitate debugging.
    ArgNotConvertibleToUtf8(OsString),
    /// Returned when a provided argument is not convertible to [NonZeroUsize].  The failing argument is
    /// provided as this variant's payload to facilitate debugging.
    ArgNotConvertibleToNonZeroUsize(usize),
    /// Returned when a provided argument is not convertible to an integer.  The original error is provided as this
    /// variant's payload to facilitate debugging.
    ParseInt(ParseIntError),
}

impl Display for Error {
    fn fmt(&self, f: &mut Formatter) -> FmtResult {
        write!(f, "{}", match self {
            Error::ArgNotConvertibleToUtf8(os_string) => format!("{}: {:?}",
                                                                 msg::ERR_ARG_NOT_CONVERTIBLE_TO_UTF_8,
                                                                 os_string),
            Error::ArgNotConvertibleToNonZeroUsize(val) => format!("{}: {:?}",
                                                                 msg::ERR_ARG_NOT_CONVERTIBLE_TO_NON_ZERO_USIZE,
                                                                 val),
            Error::ParseInt(err) => format!("{}: {}", msg::ERR_PARSE_INT, err),
        })
    }
}

impl From<OsString> for Error {
    fn from(err: OsString) -> Self {
        Error::ArgNotConvertibleToUtf8(err)
    }
}

impl From<ParseIntError> for Error {
    fn from(err: ParseIntError) -> Self {
        Error::ParseInt(err)
    }
}
